// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
cpp11::doubles fun(cpp11::strings tzone);
extern "C" SEXP _rcctzuser_fun(SEXP tzone) {
  BEGIN_CPP11
    return cpp11::as_sexp(fun(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(tzone)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _rcctzuser_fun(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rcctzuser_fun", (DL_FUNC) &_rcctzuser_fun, 1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_rcctzuser(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
